### ISSUE TITLE
Inconsistant power output label

### ISSUE THREAD

**Issue by jdelhaxhe** [Seth401/windturbines-redux#4]
The power output in the infobox do not match the power output from the electrical network chart.

In the screenshot, you can see the variation of removing / adding 1 turbine. (+- 750kW on the chart, 4MW in the infobox)

![Capture](https://user-images.githubusercontent.com/33958658/218571358-96055475-8b5d-4add-9650-c9d4fdd69bbf.JPG)
![Capture2](https://user-images.githubusercontent.com/33958658/218571361-ee77b837-15c8-4d28-83e9-2d034169d343.JPG)

**Comment by Seth401** [comment]
Could you check again with the latest version? I just pushed it on the portal as well. I haven't really been able to have that situation. If it is still present it would be cool if you could just make the save game available to me.

**Comment by jdelhaxhe** [comment]
Seems corrected !
